---
fixtures:
  repositories:
    augeas_core: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
    concat: https://github.com/simp/puppetlabs-concat.git
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld.git
    iptables: https://github.com/simp/pupmod-simp-iptables.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers.git
  symlinks:
    xinetd: "#{source_dir}"
